### ISSUE TITLE
Kubeflow v1.5 release tracker for Nutanix Karbon

### ISSUE THREAD

**Issue by johnugeorge** [nutanix/karbon-platform-services#88]
With Kubeflow 1.5 release, the progress is tracked for the following features on Nutanix Karbon with k8s 1.21

 - [x] multi-user deployment with profiles
 - [x] distributed training using Training operator(TFJob)
 - [x] Hyperparameter optimization using Katib
 - [x] Testing Inference using  KServe
 - [x]  Workflow creation using Pipelines 
 - [x] e2e-mnist manifest testing

**Comment by johnugeorge** [comment]
Tested with 1.5 RC2
