### ISSUE TITLE
Kubeflow v1.6 release tracker for Nutanix Karbon

### ISSUE THREAD

**Issue by johnugeorge** [nutanix/karbon-platform-services#94]
With Kubeflow 1.6 release, the progress is tracked for the following features on Nutanix Karbon

  - [x] multi-user deployment with profiles
  - [x] distributed training using Training operator(TFJob)
  - [x] Hyperparameter optimization using Katib
  - [x] Testing Inference using KServe
  - [x] Workflow creation using Pipelines
  - [x] e2e-mnist manifest testing

**Comment by johnugeorge** [comment]
Kubeflow manifests release [1.6.rc1 ](https://github.com/kubeflow/manifests/releases/tag/v1.6.0-rc.1) is tested against Nutanix NKE 2.5.0 with k8s 1.22
